### ISSUE TITLE
Download HF model when making docker image

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-pvnet-app#47]
## Detailed Description
Download HF model when making docker image

## Context
- Stops errors if HF is down

## Possible Implementation
TODO

**Comment by dfulu** [comment]
I accidentally took this out of the Dockerfile in a previous commit:

https://github.com/openclimatefix/pvnet_app/commit/af7fbdc84b131ecbf7241ba70ccee370bf1d68d8#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L37

I'll add it back in

**Comment by peterdudfield** [comment]
CLosing this for the moent, might focus on #225 first
