### ISSUE TITLE
Pydantic model for config

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-pvnet-app#96]
## Detailed Description
Our configuration is getting a bit more complicated. It might worth having a pydantic model, with some default values. 

## Context
- try to keep the code neat

## Possible Implementation
- Change [here](https://github.com/openclimatefix/pvnet_app/blob/main/pvnet_app/app.py#L74) to a pydantic model
- Load from yaml file
- Could be a list on model configruations
- different yaml file for "day_ahead"

**Comment by rudra2112** [comment]
Hi @peterdudfield, I would like to pick this issue. Can you elaborate on what needs to be done, so that I can move in the right direction and get started.

**Comment by peterdudfield** [comment]
Hi @rudra2112 thanks for getting in touch

We currently have big dictionary that reapeats it self sometimes - [here](https://github.com/openclimatefix/pvnet_app/blob/main/pvnet_app/app.py#L74)

I think we need to 
1. Create a pyandatic model. Perhsps the fields can be the same as the dictionary keys
2. write yaml file with these variables in it
3. load the yaml file in the main app. 
4. Have a different yaml file for the day ahead configuration https://github.com/openclimatefix/pvnet_app/blob/main/pvnet_app/app.py#L161

have you worked with pydantic before?

**Comment by rudra2112** [comment]
@peterdudfield, Thanks for the reply, Will start working on it. And Yeah I have worked a bit with Pydantic Models before.

**Comment by rudra2112** [comment]
Hey @peterdudfield, Should I replace with model_dict with a Pydantic Model with the fields pvnet_v2, pvnet_v2_sat0min_v9_batches, etc. and all its occurrences or just the the model config with pydantic model?
And how should I structure the additions? the yamls, and models.py

**Comment by peterdudfield** [comment]
Yea I would do something like that. Perhaps models.py could contain a pydantic model called `Model` and it could have the following fields
- name
- pvnet_name
- pvnet_version
- summation_name
- summation_version
- use_adjuster
- save_gsp_sum
- save_gsp_to_forecast_value_last_seven_days

you might need a second pydnatic model, call `Models` which is a list of `model`. You can then easily save the dict to yaml file and can be loaded easily. 

Does this make sense?
